markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
syntax_highlighter: rouge

encoding: utf-8
url: https://into-cps.github.io
org-url: https://into-cps-association.github.io

collections:
  netmeetings:
    output: true
  workshops:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      
